### ISSUE TITLE
Combination with Ultimate Castlevania Hack

### ISSUE THREAD

**Issue by ImJezze** [nstbayless/CV1-controls#1]
Hi, I just found out about your great hack that modernizes the controls of Castlevania and was immediately hooked. I also tried your hack in combination with another hack ([Ultimate Castlevania](http://www.romhacking.net/hacks/3736/)), that improves the graphics nicely. Unfortunately both hacks don't seem to play fully with each other. The problem that I'm facing is that you cannot walk up stairs anymore. Maybe you can have a look into this problem? It would be great if both hack would work together.

**Comment by nstbayless** [comment]
Resolved as of [Version 1.1](https://github.com/nstbayless/CV1-controls/releases/tag/v1.1)

**Comment by ImJezze** [comment]
Wonderful, thank you very much!
